import { NextResponse } from "next/server";
import { getPublicTranscript } from "../../../lib/transcript";
import {
  extractYouTubeVideoId,
  getVideoCardData,
  VideoServiceError,
} from "../../../lib/youtube";
import type { TranscriptData } from "../../../lib/video-types";

type RequestBody = {
  url?: unknown;
  transcript?: unknown;
  transcriptLanguage?: unknown;
};

const MAX_IMPORTED_TRANSCRIPT_LENGTH = 500_000;

function errorResponse(code: string, message: string, status: number) {
  return NextResponse.json({ error: { code, message } }, { status });
}

export async function POST(request: Request) {
  let body: RequestBody;

  try {
    body = (await request.json()) as RequestBody;
  } catch {
    return errorResponse(
      "INVALID_JSON",
      "A solicitação enviada não é válida.",
      400,
    );
  }

  if (typeof body.url !== "string" || body.url.length > 2_048) {
    return errorResponse(
      "INVALID_URL",
      "Informe uma URL válida do YouTube.",
      400,
    );
  }

  const importedTranscript =
    typeof body.transcript === "string" ? body.transcript.trim() : undefined;

  if (
    body.transcript !== undefined &&
    (!importedTranscript ||
      importedTranscript.length > MAX_IMPORTED_TRANSCRIPT_LENGTH)
  ) {
    return errorResponse(
      "INVALID_TRANSCRIPT",
      "A transcrição importada não é válida ou excede o limite de tamanho.",
      400,
    );
  }

  const importedLanguage =
    typeof body.transcriptLanguage === "string" &&
    body.transcriptLanguage.trim().length > 0 &&
    body.transcriptLanguage.length <= 100
      ? body.transcriptLanguage.trim()
      : "Importada do navegador";

  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) {
    return errorResponse(
      "MISSING_API_KEY",
      "A chave da API do YouTube ainda não foi configurada neste ambiente.",
      503,
    );
  }

  try {
    const videoId = extractYouTubeVideoId(body.url);
    const result = await getVideoCardData(videoId, apiKey, {
      transcriptProvider: importedTranscript
        ? async (): Promise<TranscriptData> => ({
            status: "available",
            text: importedTranscript,
            language: importedLanguage,
            isAutoGenerated: false,
          })
        : getPublicTranscript,
    });
    return NextResponse.json(result);
  } catch (error) {
    if (error instanceof VideoServiceError) {
      return errorResponse(error.code, error.message, error.status);
    }

    return errorResponse(
      "UNEXPECTED_ERROR",
      "Ocorreu um erro inesperado ao analisar o vídeo.",
      500,
    );
  }
}
