import assert from "node:assert/strict";
import test from "node:test";
import { decodeHtmlEntities } from "../lib/html-entities.ts";
import {
  extractYouTubeVideoId,
  getVideoCardData,
  VideoServiceError,
} from "../lib/youtube.ts";

test("converte entidades HTML presentes na transcrição", () => {
  assert.equal(
    decodeHtmlEntities(
      "I&#39;ll use &quot;Codex&quot; &amp; test &#x27;again&#x27;.",
    ),
    "I'll use \"Codex\" & test 'again'.",
  );
  assert.equal(decodeHtmlEntities("Duplo: &amp;#39;"), "Duplo: '");
});

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("aceita os dois formatos de URL solicitados", () => {
  assert.equal(
    extractYouTubeVideoId(
      "https://www.youtube.com/watch?v=474wZZHoWN4",
    ),
    "474wZZHoWN4",
  );
  assert.equal(
    extractYouTubeVideoId(
      "https://youtu.be/474wZZHoWN4?si=D2MPcHs9EOW8fV09",
    ),
    "474wZZHoWN4",
  );
});

test("rejeita URLs sem um identificador válido", () => {
  assert.throws(
    () => extractYouTubeVideoId("https://www.youtube.com/watch"),
    (error) =>
      error instanceof VideoServiceError &&
      error.code === "INVALID_VIDEO_ID" &&
      error.status === 400,
  );
  assert.throws(
    () => extractYouTubeVideoId("https://example.com/video"),
    (error) =>
      error instanceof VideoServiceError &&
      error.code === "UNSUPPORTED_URL",
  );
});

function createFetchMock({ hiddenSubscribers = false } = {}) {
  return async (input) => {
    const url = new URL(input.toString());

    if (url.pathname.endsWith("/videos")) {
      return Response.json({
        items: [
          {
            id: "474wZZHoWN4",
            snippet: {
              publishedAt: "2025-02-14T12:00:00Z",
              channelId: "channel-1",
              title: "Título de teste",
              description: "Descrição de teste",
              channelTitle: "Canal de teste",
              thumbnails: {
                high: { url: "https://i.ytimg.com/test.jpg" },
              },
            },
            statistics: { viewCount: "12500" },
          },
        ],
      });
    }

    return Response.json({
      items: [
        {
          statistics: hiddenSubscribers
            ? { hiddenSubscriberCount: true }
            : {
                hiddenSubscriberCount: false,
                subscriberCount: "9800",
              },
        },
      ],
    });
  };
}

test("combina dados do vídeo, canal e transcrição", async () => {
  const result = await getVideoCardData("474wZZHoWN4", "test-key", {
    fetchImpl: createFetchMock(),
    transcriptProvider: async () => ({
      status: "available",
      text: "Transcrição de teste.",
      language: "Português",
      isAutoGenerated: false,
    }),
  });

  assert.equal(result.channelName, "Canal de teste");
  assert.equal(result.viewCount, "12500");
  assert.equal(result.subscriberCount, "9800");
  assert.equal(result.transcript.status, "available");
});

test("preserva metadados quando a transcrição falha", async () => {
  const result = await getVideoCardData("474wZZHoWN4", "test-key", {
    fetchImpl: createFetchMock({ hiddenSubscribers: true }),
    transcriptProvider: async () => {
      throw new Error("captions disabled");
    },
  });

  assert.equal(result.title, "Título de teste");
  assert.equal(result.subscriberCount, null);
  assert.equal(result.subscriberCountHidden, true);
  assert.equal(result.transcript.status, "unavailable");
});

test("identifica vídeo privado, removido ou inexistente", async () => {
  await assert.rejects(
    getVideoCardData("474wZZHoWN4", "test-key", {
      fetchImpl: async () => Response.json({ items: [] }),
    }),
    (error) =>
      error instanceof VideoServiceError &&
      error.code === "VIDEO_NOT_FOUND" &&
      error.status === 404,
  );
});

test("diferencia cota excedida de chave inválida", async () => {
  const quotaFetch = async () =>
    Response.json(
      { error: { errors: [{ reason: "quotaExceeded" }] } },
      { status: 403 },
    );
  const invalidKeyFetch = async () =>
    Response.json(
      { error: { errors: [{ reason: "keyInvalid" }] } },
      { status: 400 },
    );

  await assert.rejects(
    getVideoCardData("474wZZHoWN4", "test-key", {
      fetchImpl: quotaFetch,
    }),
    (error) =>
      error instanceof VideoServiceError &&
      error.code === "QUOTA_EXCEEDED" &&
      error.status === 429,
  );
  await assert.rejects(
    getVideoCardData("474wZZHoWN4", "test-key", {
      fetchImpl: invalidKeyFetch,
    }),
    (error) =>
      error instanceof VideoServiceError &&
      error.code === "YOUTUBE_API_CONFIGURATION" &&
      error.status === 503,
  );
});

test("server-renderiza a página final", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Vídeo em Foco/);
  assert.match(html, /Tudo sobre um vídeo/);
  assert.match(html, /URL do vídeo/);
  assert.match(html, /Analisar vídeo/);
  assert.match(html, /Sua coleção de vídeos/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
