"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { decodeHtmlEntities } from "../lib/html-entities";
import { formatVideoDate } from "../lib/video-formatters";
import type { VideoCardData } from "../lib/video-types";

const EXAMPLE_URL = "https://www.youtube.com/watch?v=474wZZHoWN4";

function formatCount(value: string | null) {
  if (!value) return "Oculto";

  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return value;

  return new Intl.NumberFormat("pt-BR", {
    notation: parsed >= 10_000 ? "compact" : "standard",
    maximumFractionDigits: 1,
  }).format(parsed);
}



function ResultCard({ video }: { video: VideoCardData }) {
  const transcriptLabel =
    video.transcript.status === "available"
      ? `${video.transcript.language}${
          video.transcript.isAutoGenerated ? " · automática" : ""
        }`
      : "Indisponível";

  return (
    <article className="video-card" aria-labelledby="video-title">
      <div className="card-top">
        <div className="thumbnail-wrap">
          <img
            src={video.thumbnailUrl}
            alt={`Thumbnail do vídeo ${video.title}`}
          />
          <span className="thumbnail-badge">YouTube</span>
        </div>

        <div className="video-summary">
          <div className="channel-line">
            <span className="channel-dot" aria-hidden="true" />
            <span>{video.channelName}</span>
          </div>
          <h2 id="video-title">{video.title}</h2>

          <dl className="stats-grid">
            <div>
              <dt>Inscritos</dt>
              <dd>
                {video.subscriberCountHidden
                  ? "Oculto"
                  : formatCount(video.subscriberCount)}
              </dd>
            </div>
            <div>
              <dt>Visualizações</dt>
              <dd>{formatCount(video.viewCount)}</dd>
            </div>
            <div>
              <dt>Duração</dt>
              <dd>{video.duration ?? "Não informado"}</dd>
            </div>
            <div>
              <dt>Publicado</dt>
              <dd>{formatVideoDate(video.publishedAt)}</dd>
            </div>
          </dl>
        </div>
      </div>

      <div className="card-sections">
        <section className="content-section">
          <div className="section-heading">
            <span>01</span>
            <h3>Descrição</h3>
          </div>
          <div className="scroll-content description-content">
            {video.description || "Este vídeo não possui descrição."}
          </div>
        </section>

        <section className="content-section transcript-section">
          <div className="section-heading">
            <span>02</span>
            <h3>Transcrição</h3>
            <small>{transcriptLabel}</small>
          </div>
          <div className="scroll-content transcript-content">
            {video.transcript.status === "available"
              ? decodeHtmlEntities(video.transcript.text)
              : video.transcript.reason}
          </div>
        </section>
      </div>
    </article>
  );
}

type SavedVideo = VideoCardData & {
  savedAt: string;
};

function Collection({
  videos,
  isLoading,
  onDelete,
}: {
  videos: SavedVideo[];
  isLoading: boolean;
  onDelete: (videoId: string) => void;
}) {
  return (
    <section className="collection" aria-labelledby="collection-title">
      <div className="collection-heading">
        <div>
          <span>Arquivo pessoal</span>
          <h2 id="collection-title">Sua coleção de vídeos</h2>
        </div>
        <p>{videos.length} {videos.length === 1 ? "vídeo salvo" : "vídeos salvos"}</p>
      </div>

      {isLoading ? (
        <p className="collection-empty">Carregando sua coleção…</p>
      ) : videos.length === 0 ? (
        <p className="collection-empty">
          Os vídeos analisados aparecerão aqui para você consultar depois.
        </p>
      ) : (
        <div className="collection-grid">
          {videos.map((savedVideo) => (
            <article className="collection-card" key={savedVideo.videoId}>
              <a
                className="collection-card-open"
                href={`/videos/${savedVideo.videoId}`}
                aria-label={`Visualizar todos os detalhes de ${savedVideo.title}`}
              >
                <span className="collection-card-media">
                  <img
                    src={savedVideo.thumbnailUrl}
                    alt={`Thumbnail do vídeo ${savedVideo.title}`}
                  />
                  <span className="collection-card-status">
                    {savedVideo.transcript.status === "available"
                      ? "Transcrição disponível"
                      : "Sem transcrição"}
                  </span>
                </span>

                <span className="collection-card-body">
                  <span className="collection-card-channel">
                    <span aria-hidden="true" />
                    {savedVideo.channelName}
                  </span>
                  <strong>{savedVideo.title}</strong>

                  <span className="collection-card-stats">
                    <span>
                      <small>Visualizações</small>
                      <b>{formatCount(savedVideo.viewCount)}</b>
                    </span>
                    <span>
                      <small>Duração</small>
                      <b>{savedVideo.duration ?? "Não informado"}</b>
                    </span>
                    <span>
                      <small>Publicado</small>
                      <b>{formatVideoDate(savedVideo.publishedAt)}</b>
                    </span>
                  </span>

                  <span className="collection-card-action">
                    Ver descrição e transcrição
                    <span aria-hidden="true">→</span>
                  </span>
                </span>
              </a>
              <button
                className="collection-delete"
                type="button"
                onClick={() => onDelete(savedVideo.videoId)}
                aria-label={`Excluir ${savedVideo.title} da coleção`}
              >
                <span aria-hidden="true">×</span>
                Excluir
              </button>
            </article>
          ))}
        </div>
      )}
    </section>
  );
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [video, setVideo] = useState<VideoCardData | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [savedVideos, setSavedVideos] = useState<SavedVideo[]>([]);
  const [isCollectionLoading, setIsCollectionLoading] = useState(true);

  const refreshCollection = useCallback(async () => {
    try {
      const response = await fetch("/api/collection");
      const payload = await response.json();
      if (!response.ok) throw new Error();
      setSavedVideos(payload.videos as SavedVideo[]);
    } catch {
      setError("Não foi possível carregar sua coleção de vídeos.");
    } finally {
      setIsCollectionLoading(false);
    }
  }, []);

  useEffect(() => {
    void refreshCollection();
  }, [refreshCollection]);

  const analyzeVideo = useCallback(
    async (
      submittedUrl: string,
      importedTranscript?: string,
      importedLanguage?: string,
    ) => {
      setError("");
      setIsLoading(true);

      try {
        const response = await fetch("/api/video", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            url: submittedUrl,
            ...(importedTranscript
              ? {
                  transcript: importedTranscript,
                  transcriptLanguage: importedLanguage ?? "Importada do navegador",
                }
              : {}),
          }),
        });
        const payload = await response.json();

        if (!response.ok) {
          throw new Error(
            payload?.error?.message ??
              "Não foi possível analisar o vídeo. Tente novamente.",
          );
        }

        setVideo(payload as VideoCardData);
        await refreshCollection();
      } catch (requestError) {
        setVideo(null);
        setError(
          requestError instanceof Error
            ? requestError.message
            : "Não foi possível analisar o vídeo. Tente novamente.",
        );
      } finally {
        setIsLoading(false);
      }
    },
    [refreshCollection],
  );

  useEffect(() => {
    const handleExtensionImport = (event: MessageEvent) => {
      if (event.origin !== window.location.origin) return;

      const data = event.data;
      if (
        !data ||
        data.source !== "video-em-foco-extension" ||
        data.type !== "TRANSCRIPT_IMPORT" ||
        typeof data.payload?.url !== "string" ||
        typeof data.payload?.transcript !== "string"
      ) {
        return;
      }

      void analyzeVideo(
        data.payload.url,
        data.payload.transcript,
        typeof data.payload.language === "string"
          ? data.payload.language
          : undefined,
      );
    };

    window.addEventListener("message", handleExtensionImport);
    window.dispatchEvent(new CustomEvent("video-em-foco-ready"));

    return () => window.removeEventListener("message", handleExtensionImport);
  }, [analyzeVideo]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const submittedUrl = url.trim();
    setUrl("");
    void analyzeVideo(submittedUrl);
  }
  async function handleDelete(videoId: string) {
    try {
      const response = await fetch(`/api/collection/${videoId}`, { method: "DELETE" });
      if (!response.ok) throw new Error();
      setSavedVideos((current) => current.filter((item) => item.videoId !== videoId));
    } catch {
      setError("Não foi possível excluir este vídeo da coleção.");
    }
  }

  return (
    <main>
      <div className="background-grid" aria-hidden="true" />

      <header className="site-header">
        <a className="brand" href="#inicio" aria-label="Vídeo em Foco — início">
          <span className="brand-mark" aria-hidden="true">
            <span />
          </span>
          <span>Vídeo em Foco</span>
        </a>
        <nav className="site-nav" aria-label="Navegação principal">
          <a className="active" href="#inicio" aria-current="page">
            Vídeos
          </a>
          <a href="/knowledge-base">Base de Conhecimento</a>
        </nav>
      </header>

      <section className="hero" id="inicio">
        <div className="hero-kicker">
          <span />
          Análise direta do YouTube
        </div>
        <h1>
          Tudo sobre um vídeo,
          <br />
          <em>em um só lugar.</em>
        </h1>
        <p>
          Cole uma URL do YouTube para reunir informações do canal, desempenho,
          descrição e transcrição em um único card.
        </p>

        <form className="video-form" onSubmit={handleSubmit} noValidate>
          <label htmlFor="youtube-url">URL do vídeo</label>
          <div className="input-row">
            <input
              id="youtube-url"
              type="url"
              inputMode="url"
              autoComplete="url"
              placeholder="https://www.youtube.com/watch?v=..."
              value={url}
              onChange={(event) => setUrl(event.target.value)}
              required
              aria-describedby="url-hint"
            />
            <button type="submit" disabled={isLoading || !url.trim()}>
              {isLoading ? (
                <>
                  <span className="spinner" aria-hidden="true" />
                  Analisando
                </>
              ) : (
                <>
                  Analisar vídeo
                  <span aria-hidden="true">↗</span>
                </>
              )}
            </button>
          </div>
          <p id="url-hint" className="form-hint">
            Compatível com youtube.com/watch e youtu.be
          </p>
        </form>

        <button
          className="example-button"
          type="button"
          onClick={() => setUrl(EXAMPLE_URL)}
        >
          Usar URL de exemplo
        </button>
      </section>

      <div className="status-region" aria-live="polite">
        {error && (
          <div className="error-message" role="alert">
            <span aria-hidden="true">!</span>
            <p>{error}</p>
          </div>
        )}
        {isLoading && !video && (
          <div className="loading-card" role="status">
            <div className="loading-image" />
            <div className="loading-copy">
              <span />
              <span />
              <span />
            </div>
          </div>
        )}
      </div>

      {video && (
        <section className="selected-video" id="selected-video">
          <div className="selected-video-heading">
            <span>Vídeo selecionado</span>
            <p>Descrição e transcrição completas</p>
          </div>
          <ResultCard video={video} />
        </section>
      )}

      <Collection
        videos={savedVideos}
        isLoading={isCollectionLoading}
        onDelete={handleDelete}
      />

      <footer>
        <span>Vídeo em Foco</span>
        <p>Os dados públicos são fornecidos pela YouTube Data API.</p>
      </footer>
    </main>
  );
}

