"use client";

import { FormEvent, useState } from "react";
import type { VideoCardData } from "../lib/video-types";

const EXAMPLE_URL = "https://www.youtube.com/watch?v=474wZZHoWN4";

function formatCount(value: string | null) {
  if (!value) return "Oculto";

  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return value;

  return new Intl.NumberFormat("pt-BR", {
    notation: parsed >= 10_000 ? "compact" : "standard",
    maximumFractionDigits: 1,
  }).format(parsed);
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("pt-BR", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

function ResultCard({ video }: { video: VideoCardData }) {
  const transcriptLabel =
    video.transcript.status === "available"
      ? `${video.transcript.language}${
          video.transcript.isAutoGenerated ? " · automática" : ""
        }`
      : "Indisponível";

  return (
    <article className="video-card" aria-labelledby="video-title">
      <div className="card-top">
        <div className="thumbnail-wrap">
          <img
            src={video.thumbnailUrl}
            alt={`Thumbnail do vídeo ${video.title}`}
          />
          <span className="thumbnail-badge">YouTube</span>
        </div>

        <div className="video-summary">
          <div className="channel-line">
            <span className="channel-dot" aria-hidden="true" />
            <span>{video.channelName}</span>
          </div>
          <h2 id="video-title">{video.title}</h2>

          <dl className="stats-grid">
            <div>
              <dt>Inscritos</dt>
              <dd>
                {video.subscriberCountHidden
                  ? "Oculto"
                  : formatCount(video.subscriberCount)}
              </dd>
            </div>
            <div>
              <dt>Visualizações</dt>
              <dd>{formatCount(video.viewCount)}</dd>
            </div>
            <div>
              <dt>Publicado</dt>
              <dd>{formatDate(video.publishedAt)}</dd>
            </div>
          </dl>
        </div>
      </div>

      <div className="card-sections">
        <section className="content-section">
          <div className="section-heading">
            <span>01</span>
            <h3>Descrição</h3>
          </div>
          <div className="scroll-content description-content">
            {video.description || "Este vídeo não possui descrição."}
          </div>
        </section>

        <section className="content-section transcript-section">
          <div className="section-heading">
            <span>02</span>
            <h3>Transcrição</h3>
            <small>{transcriptLabel}</small>
          </div>
          <div className="scroll-content transcript-content">
            {video.transcript.status === "available"
              ? video.transcript.text
              : video.transcript.reason}
          </div>
        </section>
      </div>
    </article>
  );
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [video, setVideo] = useState<VideoCardData | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    setIsLoading(true);

    try {
      const response = await fetch("/api/video", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });
      const payload = await response.json();

      if (!response.ok) {
        throw new Error(
          payload?.error?.message ??
            "Não foi possível analisar o vídeo. Tente novamente.",
        );
      }

      setVideo(payload as VideoCardData);
    } catch (requestError) {
      setVideo(null);
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Não foi possível analisar o vídeo. Tente novamente.",
      );
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <main>
      <div className="background-grid" aria-hidden="true" />

      <header className="site-header">
        <a className="brand" href="#inicio" aria-label="Vídeo em Foco — início">
          <span className="brand-mark" aria-hidden="true">
            <span />
          </span>
          <span>Vídeo em Foco</span>
        </a>
        <span className="header-note">Metadados + transcrição</span>
      </header>

      <section className="hero" id="inicio">
        <div className="hero-kicker">
          <span />
          Análise direta do YouTube
        </div>
        <h1>
          Tudo sobre um vídeo,
          <br />
          <em>em um só lugar.</em>
        </h1>
        <p>
          Cole uma URL do YouTube para reunir informações do canal, desempenho,
          descrição e transcrição em um único card.
        </p>

        <form className="video-form" onSubmit={handleSubmit} noValidate>
          <label htmlFor="youtube-url">URL do vídeo</label>
          <div className="input-row">
            <input
              id="youtube-url"
              type="url"
              inputMode="url"
              autoComplete="url"
              placeholder="https://www.youtube.com/watch?v=..."
              value={url}
              onChange={(event) => setUrl(event.target.value)}
              required
              aria-describedby="url-hint"
            />
            <button type="submit" disabled={isLoading || !url.trim()}>
              {isLoading ? (
                <>
                  <span className="spinner" aria-hidden="true" />
                  Analisando
                </>
              ) : (
                <>
                  Analisar vídeo
                  <span aria-hidden="true">↗</span>
                </>
              )}
            </button>
          </div>
          <p id="url-hint" className="form-hint">
            Compatível com youtube.com/watch e youtu.be
          </p>
        </form>

        <button
          className="example-button"
          type="button"
          onClick={() => setUrl(EXAMPLE_URL)}
        >
          Usar URL de exemplo
        </button>
      </section>

      <div className="status-region" aria-live="polite">
        {error && (
          <div className="error-message" role="alert">
            <span aria-hidden="true">!</span>
            <p>{error}</p>
          </div>
        )}
        {isLoading && !video && (
          <div className="loading-card" role="status">
            <div className="loading-image" />
            <div className="loading-copy">
              <span />
              <span />
              <span />
            </div>
          </div>
        )}
      </div>

      {video && <ResultCard video={video} />}

      <footer>
        <span>Vídeo em Foco</span>
        <p>Os dados públicos são fornecidos pela YouTube Data API.</p>
      </footer>
    </main>
  );
}
