import { decodeHtmlEntities } from "../lib/html-entities";
import { formatVideoDate } from "../lib/video-formatters";
import type { VideoCardData } from "../lib/video-types";

export function formatCount(value: string | null) {
  if (!value) return "Oculto";

  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return value;

  return new Intl.NumberFormat("pt-BR", {
    notation: parsed >= 10_000 ? "compact" : "standard",
    maximumFractionDigits: 1,
  }).format(parsed);
}



export function VideoCard({ video }: { video: VideoCardData }) {
  const transcriptLabel =
    video.transcript.status === "available"
      ? `${video.transcript.language}${
          video.transcript.isAutoGenerated ? " · automática" : ""
        }`
      : "Indisponível";

  return (
    <article className="video-card" aria-labelledby="video-title">
      <div className="card-top">
        <div className="thumbnail-wrap">
          <img
            src={video.thumbnailUrl}
            alt={`Thumbnail do vídeo ${video.title}`}
          />
          <span className="thumbnail-badge">YouTube</span>
        </div>

        <div className="video-summary">
          <div className="channel-line">
            <span className="channel-dot" aria-hidden="true" />
            <span>{video.channelName}</span>
          </div>
          <h2 id="video-title">{video.title}</h2>

          <dl className="stats-grid">
            <div>
              <dt>Inscritos</dt>
              <dd>
                {video.subscriberCountHidden
                  ? "Oculto"
                  : formatCount(video.subscriberCount)}
              </dd>
            </div>
            <div>
              <dt>Visualizações</dt>
              <dd>{formatCount(video.viewCount)}</dd>
            </div>
            <div>
              <dt>Duração</dt>
              <dd>{video.duration ?? "Não informado"}</dd>
            </div>
            <div>
              <dt>Publicado</dt>
              <dd>{formatVideoDate(video.publishedAt)}</dd>
            </div>
          </dl>
        </div>
      </div>

      <div className="card-sections">
        <section className="content-section">
          <div className="section-heading">
            <span>01</span>
            <h3>Descrição</h3>
          </div>
          <div className="scroll-content description-content">
            {video.description || "Este vídeo não possui descrição."}
          </div>
        </section>

        <section className="content-section transcript-section">
          <div className="section-heading">
            <span>02</span>
            <h3>Transcrição</h3>
            <small>{transcriptLabel}</small>
          </div>
          <div className="scroll-content transcript-content">
            {video.transcript.status === "available"
              ? decodeHtmlEntities(video.transcript.text)
              : video.transcript.reason}
          </div>
        </section>
      </div>
    </article>
  );
}
