import {
  fetchTranscript,
  listLanguages,
  toPlainText,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptTooManyRequestError,
} from "youtube-transcript-plus";
import { decodeHtmlEntities } from "./html-entities";
import type { FetchParams } from "youtube-transcript-plus";
import type { TranscriptData } from "./video-types";

const LANGUAGE_PRIORITY = ["pt-BR", "pt", "en"];
const TRANSCRIPT_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
function fetchPlayerWithWebClient(params: FetchParams): Promise<Response> {
  const payload = params.body ? (JSON.parse(params.body) as object) : {};

  return fetch(params.url, {
    method: params.method ?? "POST",
    headers: {
      ...params.headers,
      "Accept-Language": params.lang ?? "pt-BR",
      "User-Agent": params.userAgent ?? TRANSCRIPT_USER_AGENT,
      "X-YouTube-Client-Name": "1",
      "X-YouTube-Client-Version": "2.20250206.00.00",
    },
    body: JSON.stringify({
      ...payload,
      context: {
        client: {
          clientName: "WEB",
          clientVersion: "2.20250206.00.00",
        },
      },
    }),
    signal: params.signal,
  });
}
function getTranscriptUnavailableReason(error: unknown): string {
  if (error instanceof YoutubeTranscriptTooManyRequestError) {
    return "O YouTube limitou temporariamente a consulta de legendas. Aguarde alguns minutos e tente novamente.";
  }

  if (error instanceof YoutubeTranscriptDisabledError) {
    return "Este vídeo não disponibiliza legendas para transcrição.";
  }

  if (error instanceof YoutubeTranscriptNotAvailableError) {
    return "Este vídeo não possui legendas públicas disponíveis para transcrição.";
  }

  if (error instanceof TypeError && error.message === "fetch failed") {
    return "Não foi possível conectar ao serviço de legendas do YouTube. Verifique sua rede e tente novamente.";
  }

  return "A transcrição não está disponível para este vídeo. As legendas podem estar restritas ou temporariamente inacessíveis.";
}

export async function getPublicTranscript(
  videoId: string,
): Promise<TranscriptData> {
  try {
    const languages = await listLanguages(videoId, {
      userAgent: TRANSCRIPT_USER_AGENT,
      retries: 2,
      retryDelay: 1_000,
      signal: AbortSignal.timeout(15_000),
      playerFetch: fetchPlayerWithWebClient,
    });
    if (!languages.length) {
      return {
        status: "unavailable",
        reason:
          "Este vídeo não possui legendas públicas disponíveis para transcrição.",
      };
    }

    const selected =
      LANGUAGE_PRIORITY.map((language) =>
        languages.find(
          (track) =>
            track.languageCode.toLowerCase() === language.toLowerCase(),
        ),
      ).find(Boolean) ??
      languages.find((track) => !track.isAutoGenerated) ??
      languages[0];

    const segments = await fetchTranscript(videoId, {
      lang: selected.languageCode,
      retries: 1,
      retryDelay: 1_000,
      signal: AbortSignal.timeout(15_000),
      userAgent: TRANSCRIPT_USER_AGENT,
      playerFetch: fetchPlayerWithWebClient,
    });
    const text = decodeHtmlEntities(toPlainText(segments)).trim();

    if (!text) {
      return {
        status: "unavailable",
        reason:
          "As legendas deste vídeo estão vazias ou não puderam ser interpretadas.",
      };
    }

    return {
      status: "available",
      text,
      language: selected.languageName || selected.languageCode,
      isAutoGenerated: selected.isAutoGenerated,
    };
  } catch (error) {
    console.warn("Não foi possível obter a transcrição pública do YouTube.", {
      videoId,
      error: error instanceof Error ? error.message : String(error),
    });
    return {
      status: "unavailable",
      reason: getTranscriptUnavailableReason(error),
    };
  }
}
