import {
  fetchTranscript,
  listLanguages,
  toPlainText,
} from "youtube-transcript-plus";
import { decodeHtmlEntities } from "./html-entities";
import type { TranscriptData } from "./video-types";

const LANGUAGE_PRIORITY = ["pt-BR", "pt", "en"];

export async function getPublicTranscript(
  videoId: string,
): Promise<TranscriptData> {
  try {
    const languages = await listLanguages(videoId);
    if (!languages.length) {
      return {
        status: "unavailable",
        reason:
          "Este vídeo não possui legendas públicas disponíveis para transcrição.",
      };
    }

    const selected =
      LANGUAGE_PRIORITY.map((language) =>
        languages.find(
          (track) =>
            track.languageCode.toLowerCase() === language.toLowerCase(),
        ),
      ).find(Boolean) ??
      languages.find((track) => !track.isAutoGenerated) ??
      languages[0];

    const segments = await fetchTranscript(videoId, {
      lang: selected.languageCode,
      retries: 1,
      retryDelay: 500,
      signal: AbortSignal.timeout(15_000),
    });
    const text = decodeHtmlEntities(toPlainText(segments)).trim();

    if (!text) {
      return {
        status: "unavailable",
        reason:
          "As legendas deste vídeo estão vazias ou não puderam ser interpretadas.",
      };
    }

    return {
      status: "available",
      text,
      language: selected.languageName || selected.languageCode,
      isAutoGenerated: selected.isAutoGenerated,
    };
  } catch {
    return {
      status: "unavailable",
      reason:
        "A transcrição não está disponível para este vídeo. As legendas podem estar desativadas, restritas ou temporariamente inacessíveis.",
    };
  }
}
