export type TranscriptData =
  | {
      status: "available";
      text: string;
      language: string;
      isAutoGenerated: boolean;
    }
  | {
      status: "unavailable";
      reason: string;
    };

export type VideoCardData = {
  videoId: string;
  thumbnailUrl: string;
  channelName: string;
  title: string;
  subscriberCount: string | null;
  subscriberCountHidden: boolean;
  viewCount: string;
  publishedAt: string;
  description: string;
  transcript: TranscriptData;
};
